version: "3.8"
services:
  web:
    image: ahmedmohamed1101140/tradebyte:latest
    command: python hello.py
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=DEV
      - HOST=localhost
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    networks:
      - prod-network
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - prod-network
networks:
  prod-network:
    driver: "bridge"
volumes:
  cache:
    driver: local

