version: "3.8"
services:
  web:
    image: ahmedmohamed1101140/tradebyte:dev
    command: python hello.py
    ports:
      - 9000:9000
    environment:
      - ENVIRONMENT=DEV
      - HOST=localhost
      - PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - REDIS_DB=0
    depends_on:
      - redis
    networks:
      - dev-network
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - cache:/data
    networks:
      - dev-network
networks:
  dev-network:
    driver: "bridge"
volumes:
  cache:
    driver: local

