version: "3.8"
services:
  web:
    image: ahmedmohamed1101140/tradebyte:test
    command: python hello.py
    ports:
      - 9000:9000
    environment:
      - ENVIRONMENT=DEV
      - HOST=localhost
      - PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - "6379:6379"
