name: Python CI/CD DEV

on: 
  push:
    branches: [ dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code so it can be run by GitHub
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - run: echo "Python has been set up."
       
      - name: Run the Python code in helloworld.py
        run: |
          echo "Running Python code"
          python tests/test.py
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tradebyte:dev
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Update Docker Compose File on VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "docker-compose.yml"
        target: "/home/ubuntu/tradebyte-app-dev"
          

    - name: Deploy Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/ubuntu/tradebyte-app-dev
          docker-compose down
          docker-compose up -d
